# Generated by Selenium IDE
import time
from selenium import webdriver
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.by import By


class TestUntitled():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_untitled(self):
        # Test name: Untitled
        # Step # | name | target | value
        # 1 | open | / |
        self.driver.get("https://www.baidu.com/")
        # 2 | setWindowSize | 964x594 |
        self.driver.set_window_size(964, 594)
        # 3 | click | id=kw |
        self.driver.find_element(By.ID, "kw").click()
        # 4 | mouseOver | id=su |
        element = self.driver.find_element(By.ID, "su")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        # 5 | type | id=kw | 测试人社区
        self.driver.find_element(By.ID, "kw").send_keys("测试人社区")
        # 6 | click | id=su |
        self.driver.find_element(By.ID, "su").click()
        time.sleep(3)
        # IDE录制的脚本无法确定是否执行成功或失败
        # 需要添加断言信息:判断搜索列表中是否包含输入的kw

        res_elements = self.driver.find_elements(By.TAG_NAME, "em")
        for i in res_elements:
            try:
                assert "测试人社区" == i.text
            except:
                continue
            else:
                break
        else:
            raise AssertionError
