# Generated by Selenium IDE
import time
from selenium import webdriver
from selenium.webdriver.common.by import By


class Test_web():
    def setup(self):
        self.driver = webdriver.Chrome()
        self.driver.implicitly_wait(3)

    def teardown(self):
        self.driver.quit()

    def test_case1(self):
        # Test name: 测试人论坛搜索
        # Step # | name | target | value
        # 1 | open | / |
        self.driver.get("https://ceshiren.com/")
        # 2 | setWindowSize | 964x594 |
        self.driver.set_window_size(964, 594)
        # 3 | click | id=search-button |
        self.driver.find_element(By.ID, "search-button").click()
        # 4 | click | css=.d-icon-sliders-h |
        self.driver.find_element(By.CSS_SELECTOR, ".d-icon-sliders-h").click()
        # 5 | click | css=[aria-label='输入搜索关键字'] |
        self.driver.find_element(By.CSS_SELECTOR, "[aria-label='输入搜索关键字']").click()
        # 6 | type | css=[aria-label='输入搜索关键字']| python
        self.driver.find_element(By.CSS_SELECTOR, "[aria-label='输入搜索关键字']").send_keys("python")
        # 7 | click | css=.d-button-label |
        self.driver.find_element(By.CSS_SELECTOR, ".d-button-label").click()
        time.sleep(2)
        # 8 | assert | id="create-account-title"
        res_element = self.driver.find_element(By.ID, "create-account-title")
        content = """欢迎！\n让我们创建您的帐户"""
        assert res_element.text == content
